import Head from 'next/head';
import { useEffect } from 'react';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { TextField, Button, Typography } from '@mui/material';
import Classes from '../styles/login.module.css';

export default function Register() {
	const router = useRouter();
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');



	useEffect(() => {
		let token = window.sessionStorage.getItem('Token');

		if (token) {
			router.push('/');
		}
	}, []);

	return (
		<div>
			<Head>
				<title>Next CRUD AUTH</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={Classes.loginMain}>
				<h1>Login</h1>

				<TextField
					placeholder="Email"
					onChange={(event) => setEmail(event.target.value)}
					value={email}
					type="email"
				/>
				<TextField
					placeholder="Password"
					onChange={(event) => setPassword(event.target.value)}
					value={password}
					type="password"
				/>

				<Button variant="contained" onClick={signUp}>
					Sign In
				</Button>
				<hr />
				<Typography>or sign in using:</Typography>
				<Button variant="outlined" onClick={signUpWithGoogle}>
					Google
				</Button>
				<Button variant="outlined" onClick={signUpWithGithub}>
					Github
				</Button>
				<Typography variant="overline">Don't have an account?</Typography>
				<hr />
				<Button
					sx={{ width: '30%' }}
					variant="contained"
					onClick={() => {
						router.push('/register');
					}}>
					Sign up
				</Button>
			</main>
		</div>
	);
}
